import { Container, CssBaseline } from '@mui/material'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/header'
import Providers from './providers'
import { authenticate } from './auth/actions/authenticated'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const authenticated = await authenticate()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers authenticated={authenticated}>
          <CssBaseline />
          <Header />
          <Container className={authenticated ? 'mt-10' : ''}>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  )
}
